### PR TITLE
Feature/traduction

### PR DESCRIPTION
**Pull request by armandfardeau**

### CODE REVIEW

**Comment by virgile-dev** [comment]
I committed the right translation on the branch. I thought I had forked the repo and meant to do PR. Sorry if I broke anything.

**Comment by armandfardeau** [comment]
> I committed the right translation on the branch. I thought I had forked the repo and meant to do PR. Sorry if I broke anything.

https://youtu.be/D9-voINFkCg?t=94

**Comment by armandfardeau** [comment]
> I need 2 different `subject` for the notifications one for reported and one for blocked could you make the changes ?

There is only one mail sent for this task.

**Review by paulinebessoles — APPROVED** [review]

**Comment by Quentinchampenois** [comment]
Good to me

**Pull request merged**
